version: '3.1'

services:
  wordpress:
    image: ttungbmt/wordpress
    build: 
      context: .
      args:
        WORDPRESS_VERSION: '${WORDPRESS_VERSION}'
        USER: '${USER:-ubuntu}'
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    ports:
      - ${FORWARD_WORDPRESS_PORT}:80
    environment:
      APACHE_RUN_GROUP: '${USER:-ubuntu}'
      APACHE_RUN_USER: '${USER:-ubuntu}'
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WP_DEBUG:-false}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_HOME}');
        define('WP_SITEURL', '${WP_SITEURL}');
        define('WP_ALLOW_MULTISITE', true);
        define('WP_CACHE', true);
        define('WP_POST_REVISIONS', 25);
        define('FS_METHOD', 'direct');
        define('EMPTY_TRASH_DAYS', 365);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '1024M');
    volumes:
      - ./src:/var/www/html
